sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# build image
- docker build -t hukam/rpi-motion-detection .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV BUILD_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag hukam/rpi-motion-detection hukam/rpi-motion-detection:$BUILD_VERSION
    docker push hukam/rpi-motion-detection:$BUILD_VERSION
    docker push hukam/rpi-motion-detection
  fi
